// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: protocol/proxyu.proto

package protocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CorrelationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CorrelationRequest) Reset() {
	*x = CorrelationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CorrelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelationRequest) ProtoMessage() {}

func (x *CorrelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelationRequest.ProtoReflect.Descriptor instead.
func (*CorrelationRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{0}
}

type CorrelationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*CorrelationResponse_CorrelationMessage
	//	*CorrelationResponse_PublicKey
	Response isCorrelationResponse_Response `protobuf_oneof:"response"`
}

func (x *CorrelationResponse) Reset() {
	*x = CorrelationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CorrelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CorrelationResponse) ProtoMessage() {}

func (x *CorrelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CorrelationResponse.ProtoReflect.Descriptor instead.
func (*CorrelationResponse) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{1}
}

func (m *CorrelationResponse) GetResponse() isCorrelationResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *CorrelationResponse) GetCorrelationMessage() string {
	if x, ok := x.GetResponse().(*CorrelationResponse_CorrelationMessage); ok {
		return x.CorrelationMessage
	}
	return ""
}

func (x *CorrelationResponse) GetPublicKey() []byte {
	if x, ok := x.GetResponse().(*CorrelationResponse_PublicKey); ok {
		return x.PublicKey
	}
	return nil
}

type isCorrelationResponse_Response interface {
	isCorrelationResponse_Response()
}

type CorrelationResponse_CorrelationMessage struct {
	CorrelationMessage string `protobuf:"bytes,1,opt,name=correlation_message,json=correlationMessage,proto3,oneof"`
}

type CorrelationResponse_PublicKey struct {
	PublicKey []byte `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3,oneof"` // 32 bytes ed25519 public key
}

func (*CorrelationResponse_CorrelationMessage) isCorrelationResponse_Response() {}

func (*CorrelationResponse_PublicKey) isCorrelationResponse_Response() {}

type SubmitDocumentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url  string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Hash []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"` // 32 bytes SHA3-256 hash
}

func (x *SubmitDocumentRequest) Reset() {
	*x = SubmitDocumentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDocumentRequest) ProtoMessage() {}

func (x *SubmitDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDocumentRequest.ProtoReflect.Descriptor instead.
func (*SubmitDocumentRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitDocumentRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SubmitDocumentRequest) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type SubmitDocumentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *SubmitDocumentResponse) Reset() {
	*x = SubmitDocumentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitDocumentResponse) ProtoMessage() {}

func (x *SubmitDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitDocumentResponse.ProtoReflect.Descriptor instead.
func (*SubmitDocumentResponse) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitDocumentResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SubmitDocumentResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PermissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 32 bytes ed25519 public key
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                            // 16 bytes UUIDv4
	Process   []byte `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`                      // 16 bytes UUIDv4
	Reason    []byte `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                        // 16 bytes UUIDv4
	Policy    []byte `protobuf:"bytes,5,opt,name=policy,proto3" json:"policy,omitempty"`                        // 32 bytes SHA3-256 hash
	From      uint64 `protobuf:"varint,6,opt,name=from,proto3" json:"from,omitempty"`                           // Unix UTC timestamp
	Until     uint64 `protobuf:"varint,7,opt,name=until,proto3" json:"until,omitempty"`                         // Unix UTC timestamp
	Amount    uint32 `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
	Level     uint32 `protobuf:"varint,9,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *PermissionRequest) Reset() {
	*x = PermissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionRequest) ProtoMessage() {}

func (x *PermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionRequest.ProtoReflect.Descriptor instead.
func (*PermissionRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{4}
}

func (x *PermissionRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PermissionRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PermissionRequest) GetProcess() []byte {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *PermissionRequest) GetReason() []byte {
	if x != nil {
		return x.Reason
	}
	return nil
}

func (x *PermissionRequest) GetPolicy() []byte {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *PermissionRequest) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *PermissionRequest) GetUntil() uint64 {
	if x != nil {
		return x.Until
	}
	return 0
}

func (x *PermissionRequest) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PermissionRequest) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type PermissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*PermissionResponse_PermissionMessage
	//	*PermissionResponse_Granted
	Response isPermissionResponse_Response `protobuf_oneof:"response"`
}

func (x *PermissionResponse) Reset() {
	*x = PermissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionResponse) ProtoMessage() {}

func (x *PermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionResponse.ProtoReflect.Descriptor instead.
func (*PermissionResponse) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{5}
}

func (m *PermissionResponse) GetResponse() isPermissionResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *PermissionResponse) GetPermissionMessage() string {
	if x, ok := x.GetResponse().(*PermissionResponse_PermissionMessage); ok {
		return x.PermissionMessage
	}
	return ""
}

func (x *PermissionResponse) GetGranted() bool {
	if x, ok := x.GetResponse().(*PermissionResponse_Granted); ok {
		return x.Granted
	}
	return false
}

type isPermissionResponse_Response interface {
	isPermissionResponse_Response()
}

type PermissionResponse_PermissionMessage struct {
	PermissionMessage string `protobuf:"bytes,1,opt,name=permission_message,json=permissionMessage,proto3,oneof"`
}

type PermissionResponse_Granted struct {
	Granted bool `protobuf:"varint,2,opt,name=granted,proto3,oneof"`
}

func (*PermissionResponse_PermissionMessage) isPermissionResponse_Response() {}

func (*PermissionResponse_Granted) isPermissionResponse_Response() {}

type DataField struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid  []byte `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"` // 16 bytes UUIDv4
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Mime  string `protobuf:"bytes,3,opt,name=mime,proto3" json:"mime,omitempty"`
}

func (x *DataField) Reset() {
	*x = DataField{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataField) ProtoMessage() {}

func (x *DataField) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataField.ProtoReflect.Descriptor instead.
func (*DataField) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{6}
}

func (x *DataField) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *DataField) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DataField) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

type DataRetrieveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 32 bytes ed25519 public key
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                            // 16 bytes UUIDv4
	Process   []byte `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`                      // 16 bytes UUIDv4
}

func (x *DataRetrieveRequest) Reset() {
	*x = DataRetrieveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRetrieveRequest) ProtoMessage() {}

func (x *DataRetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRetrieveRequest.ProtoReflect.Descriptor instead.
func (*DataRetrieveRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{7}
}

func (x *DataRetrieveRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *DataRetrieveRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataRetrieveRequest) GetProcess() []byte {
	if x != nil {
		return x.Process
	}
	return nil
}

type DataRetrieveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte       `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 32 bytes ed25519 public key
	Data      []byte       `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                            // 16 bytes UUIDv4
	Process   []byte       `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`                      // 16 bytes UUIDv4
	Error     int32        `protobuf:"zigzag32,4,opt,name=error,proto3" json:"error,omitempty"`
	Fields    []*DataField `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"`
}

func (x *DataRetrieveResponse) Reset() {
	*x = DataRetrieveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRetrieveResponse) ProtoMessage() {}

func (x *DataRetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRetrieveResponse.ProtoReflect.Descriptor instead.
func (*DataRetrieveResponse) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{8}
}

func (x *DataRetrieveResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *DataRetrieveResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataRetrieveResponse) GetProcess() []byte {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *DataRetrieveResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *DataRetrieveResponse) GetFields() []*DataField {
	if x != nil {
		return x.Fields
	}
	return nil
}

type DataSupplyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 32 bytes ed25519 public key
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                            // 16 bytes UUIDv4
	Process   []byte `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`                      // 16 bytes UUIDv4
	Value     []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Mime      string `protobuf:"bytes,5,opt,name=mime,proto3" json:"mime,omitempty"`
}

func (x *DataSupplyRequest) Reset() {
	*x = DataSupplyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataSupplyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSupplyRequest) ProtoMessage() {}

func (x *DataSupplyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSupplyRequest.ProtoReflect.Descriptor instead.
func (*DataSupplyRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{9}
}

func (x *DataSupplyRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *DataSupplyRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataSupplyRequest) GetProcess() []byte {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *DataSupplyRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *DataSupplyRequest) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

type DataSupplyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 32 bytes ed25519 public key
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                            // 16 bytes UUIDv4
	Process   []byte `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`                      // 16 bytes UUIDv4
	Error     int32  `protobuf:"zigzag32,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DataSupplyResponse) Reset() {
	*x = DataSupplyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataSupplyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataSupplyResponse) ProtoMessage() {}

func (x *DataSupplyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataSupplyResponse.ProtoReflect.Descriptor instead.
func (*DataSupplyResponse) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{10}
}

func (x *DataSupplyResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *DataSupplyResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataSupplyResponse) GetProcess() []byte {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *DataSupplyResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

type DataDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 32 bytes ed25519 public key
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                            // 16 bytes UUIDv4
	Process   []byte `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`                      // 16 bytes UUIDv4
}

func (x *DataDeleteRequest) Reset() {
	*x = DataDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDeleteRequest) ProtoMessage() {}

func (x *DataDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDeleteRequest.ProtoReflect.Descriptor instead.
func (*DataDeleteRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{11}
}

func (x *DataDeleteRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *DataDeleteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataDeleteRequest) GetProcess() []byte {
	if x != nil {
		return x.Process
	}
	return nil
}

type DataDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // 32 bytes ed25519 public key
	Data      []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                            // 16 bytes UUIDv4
	Process   []byte `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`                      // 16 bytes UUIDv4
	Error     int32  `protobuf:"zigzag32,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *DataDeleteResponse) Reset() {
	*x = DataDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDeleteResponse) ProtoMessage() {}

func (x *DataDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDeleteResponse.ProtoReflect.Descriptor instead.
func (*DataDeleteResponse) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{12}
}

func (x *DataDeleteResponse) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *DataDeleteResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataDeleteResponse) GetProcess() []byte {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *DataDeleteResponse) GetError() int32 {
	if x != nil {
		return x.Error
	}
	return 0
}

type DataNopRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DataNopRequest) Reset() {
	*x = DataNopRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataNopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataNopRequest) ProtoMessage() {}

func (x *DataNopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataNopRequest.ProtoReflect.Descriptor instead.
func (*DataNopRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{13}
}

type DataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//	*DataRequest_RetrieveRequest
	//	*DataRequest_RetrieveResponse
	//	*DataRequest_SupplyResponse
	//	*DataRequest_DeleteResponse
	//	*DataRequest_NopRequest
	Request isDataRequest_Request `protobuf_oneof:"request"`
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{14}
}

func (m *DataRequest) GetRequest() isDataRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *DataRequest) GetRetrieveRequest() *DataRetrieveRequest {
	if x, ok := x.GetRequest().(*DataRequest_RetrieveRequest); ok {
		return x.RetrieveRequest
	}
	return nil
}

func (x *DataRequest) GetRetrieveResponse() *DataRetrieveResponse {
	if x, ok := x.GetRequest().(*DataRequest_RetrieveResponse); ok {
		return x.RetrieveResponse
	}
	return nil
}

func (x *DataRequest) GetSupplyResponse() *DataSupplyResponse {
	if x, ok := x.GetRequest().(*DataRequest_SupplyResponse); ok {
		return x.SupplyResponse
	}
	return nil
}

func (x *DataRequest) GetDeleteResponse() *DataDeleteResponse {
	if x, ok := x.GetRequest().(*DataRequest_DeleteResponse); ok {
		return x.DeleteResponse
	}
	return nil
}

func (x *DataRequest) GetNopRequest() *DataNopRequest {
	if x, ok := x.GetRequest().(*DataRequest_NopRequest); ok {
		return x.NopRequest
	}
	return nil
}

type isDataRequest_Request interface {
	isDataRequest_Request()
}

type DataRequest_RetrieveRequest struct {
	RetrieveRequest *DataRetrieveRequest `protobuf:"bytes,1,opt,name=retrieve_request,json=retrieveRequest,proto3,oneof"`
}

type DataRequest_RetrieveResponse struct {
	RetrieveResponse *DataRetrieveResponse `protobuf:"bytes,2,opt,name=retrieve_response,json=retrieveResponse,proto3,oneof"`
}

type DataRequest_SupplyResponse struct {
	SupplyResponse *DataSupplyResponse `protobuf:"bytes,3,opt,name=supply_response,json=supplyResponse,proto3,oneof"`
}

type DataRequest_DeleteResponse struct {
	DeleteResponse *DataDeleteResponse `protobuf:"bytes,4,opt,name=delete_response,json=deleteResponse,proto3,oneof"`
}

type DataRequest_NopRequest struct {
	NopRequest *DataNopRequest `protobuf:"bytes,5,opt,name=nop_request,json=nopRequest,proto3,oneof"`
}

func (*DataRequest_RetrieveRequest) isDataRequest_Request() {}

func (*DataRequest_RetrieveResponse) isDataRequest_Request() {}

func (*DataRequest_SupplyResponse) isDataRequest_Request() {}

func (*DataRequest_DeleteResponse) isDataRequest_Request() {}

func (*DataRequest_NopRequest) isDataRequest_Request() {}

type DataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*DataResponse_RetrieveRequest
	//	*DataResponse_RetrieveResponse
	//	*DataResponse_SupplyRequest
	//	*DataResponse_DeleteRequest
	Response isDataResponse_Response `protobuf_oneof:"response"`
}

func (x *DataResponse) Reset() {
	*x = DataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_proxyu_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataResponse) ProtoMessage() {}

func (x *DataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proxyu_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataResponse.ProtoReflect.Descriptor instead.
func (*DataResponse) Descriptor() ([]byte, []int) {
	return file_protocol_proxyu_proto_rawDescGZIP(), []int{15}
}

func (m *DataResponse) GetResponse() isDataResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *DataResponse) GetRetrieveRequest() *DataRetrieveRequest {
	if x, ok := x.GetResponse().(*DataResponse_RetrieveRequest); ok {
		return x.RetrieveRequest
	}
	return nil
}

func (x *DataResponse) GetRetrieveResponse() *DataRetrieveResponse {
	if x, ok := x.GetResponse().(*DataResponse_RetrieveResponse); ok {
		return x.RetrieveResponse
	}
	return nil
}

func (x *DataResponse) GetSupplyRequest() *DataSupplyRequest {
	if x, ok := x.GetResponse().(*DataResponse_SupplyRequest); ok {
		return x.SupplyRequest
	}
	return nil
}

func (x *DataResponse) GetDeleteRequest() *DataDeleteRequest {
	if x, ok := x.GetResponse().(*DataResponse_DeleteRequest); ok {
		return x.DeleteRequest
	}
	return nil
}

type isDataResponse_Response interface {
	isDataResponse_Response()
}

type DataResponse_RetrieveRequest struct {
	RetrieveRequest *DataRetrieveRequest `protobuf:"bytes,1,opt,name=retrieve_request,json=retrieveRequest,proto3,oneof"`
}

type DataResponse_RetrieveResponse struct {
	RetrieveResponse *DataRetrieveResponse `protobuf:"bytes,2,opt,name=retrieve_response,json=retrieveResponse,proto3,oneof"`
}

type DataResponse_SupplyRequest struct {
	SupplyRequest *DataSupplyRequest `protobuf:"bytes,3,opt,name=supply_request,json=supplyRequest,proto3,oneof"`
}

type DataResponse_DeleteRequest struct {
	DeleteRequest *DataDeleteRequest `protobuf:"bytes,4,opt,name=delete_request,json=deleteRequest,proto3,oneof"`
}

func (*DataResponse_RetrieveRequest) isDataResponse_Response() {}

func (*DataResponse_RetrieveResponse) isDataResponse_Response() {}

func (*DataResponse_SupplyRequest) isDataResponse_Response() {}

func (*DataResponse_DeleteRequest) isDataResponse_Response() {}

var File_protocol_proxyu_proto protoreflect.FileDescriptor

var file_protocol_proxyu_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x22, 0x14, 0x0a, 0x12, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x75, 0x0a, 0x13, 0x43, 0x6f, 0x72, 0x72, 0x65,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x13, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x12, 0x63,
	0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3d,
	0x0a, 0x15, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73,
	0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22, 0x3e, 0x0a,
	0x16, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xe8, 0x01,
	0x0a, 0x11, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b,
	0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x6c, 0x69,
	0x63, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x70, 0x6f, 0x6c, 0x69, 0x63, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04,
	0x66, 0x72, 0x6f, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x05, 0x75, 0x6e, 0x74, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22, 0x6d, 0x0a, 0x12, 0x50, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f,
	0x0a, 0x12, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x11, 0x70, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x1a, 0x0a, 0x07, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x48, 0x00, 0x52, 0x07, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x49, 0x0a, 0x09, 0x44, 0x61, 0x74, 0x61, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6d, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x69,
	0x6d, 0x65, 0x22, 0x62, 0x0a, 0x13, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x22, 0xa6, 0x01, 0x0a, 0x14, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x11, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x2b, 0x0a, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x06, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x22,
	0x8a, 0x01, 0x0a, 0x11, 0x44, 0x61, 0x74, 0x61, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x69, 0x6d, 0x65, 0x22, 0x77, 0x0a, 0x12,
	0x44, 0x61, 0x74, 0x61, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x11, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x60, 0x0a, 0x11, 0x44, 0x61, 0x74, 0x61, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x22, 0x77, 0x0a, 0x12, 0x44, 0x61, 0x74, 0x61, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x11, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x10, 0x0a, 0x0e, 0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x82, 0x03, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x4a, 0x0a, 0x10, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x5f, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0f, 0x72,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x4d,
	0x0a, 0x11, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x10, 0x72, 0x65, 0x74,
	0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a,
	0x0f, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52,
	0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3b, 0x0a, 0x0b, 0x6e, 0x6f, 0x70, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x4e, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x0a, 0x6e, 0x6f, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x09, 0x0a, 0x07,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xc1, 0x02, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4a, 0x0a, 0x10, 0x72, 0x65, 0x74, 0x72,
	0x69, 0x65, 0x76, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x48, 0x00, 0x52, 0x0f, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x4d, 0x0a, 0x11, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48,
	0x00, 0x52, 0x10, 0x72, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0e, 0x73, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x5f, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x53, 0x75, 0x70, 0x70, 0x6c,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x73, 0x75, 0x70, 0x70,
	0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x44, 0x0a, 0x0e, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00,
	0x52, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42,
	0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xbc, 0x02, 0x0a, 0x11,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x55, 0x49, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x4c, 0x0a, 0x0b, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6f, 0x72, 0x72,
	0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x43, 0x6f, 0x72, 0x72, 0x65, 0x6c,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12,
	0x53, 0x0a, 0x0e, 0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x75, 0x62,
	0x6d, 0x69, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x53, 0x75,
	0x62, 0x6d, 0x69, 0x74, 0x44, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x30, 0x01, 0x12,
	0x39, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x63, 0x65, 0x32, 0x68, 0x65, 0x61,
	0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x75, 0x5f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protocol_proxyu_proto_rawDescOnce sync.Once
	file_protocol_proxyu_proto_rawDescData = file_protocol_proxyu_proto_rawDesc
)

func file_protocol_proxyu_proto_rawDescGZIP() []byte {
	file_protocol_proxyu_proto_rawDescOnce.Do(func() {
		file_protocol_proxyu_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_proxyu_proto_rawDescData)
	})
	return file_protocol_proxyu_proto_rawDescData
}

var file_protocol_proxyu_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_protocol_proxyu_proto_goTypes = []interface{}{
	(*CorrelationRequest)(nil),     // 0: protocol.CorrelationRequest
	(*CorrelationResponse)(nil),    // 1: protocol.CorrelationResponse
	(*SubmitDocumentRequest)(nil),  // 2: protocol.SubmitDocumentRequest
	(*SubmitDocumentResponse)(nil), // 3: protocol.SubmitDocumentResponse
	(*PermissionRequest)(nil),      // 4: protocol.PermissionRequest
	(*PermissionResponse)(nil),     // 5: protocol.PermissionResponse
	(*DataField)(nil),              // 6: protocol.DataField
	(*DataRetrieveRequest)(nil),    // 7: protocol.DataRetrieveRequest
	(*DataRetrieveResponse)(nil),   // 8: protocol.DataRetrieveResponse
	(*DataSupplyRequest)(nil),      // 9: protocol.DataSupplyRequest
	(*DataSupplyResponse)(nil),     // 10: protocol.DataSupplyResponse
	(*DataDeleteRequest)(nil),      // 11: protocol.DataDeleteRequest
	(*DataDeleteResponse)(nil),     // 12: protocol.DataDeleteResponse
	(*DataNopRequest)(nil),         // 13: protocol.DataNopRequest
	(*DataRequest)(nil),            // 14: protocol.DataRequest
	(*DataResponse)(nil),           // 15: protocol.DataResponse
}
var file_protocol_proxyu_proto_depIdxs = []int32{
	6,  // 0: protocol.DataRetrieveResponse.fields:type_name -> protocol.DataField
	7,  // 1: protocol.DataRequest.retrieve_request:type_name -> protocol.DataRetrieveRequest
	8,  // 2: protocol.DataRequest.retrieve_response:type_name -> protocol.DataRetrieveResponse
	10, // 3: protocol.DataRequest.supply_response:type_name -> protocol.DataSupplyResponse
	12, // 4: protocol.DataRequest.delete_response:type_name -> protocol.DataDeleteResponse
	13, // 5: protocol.DataRequest.nop_request:type_name -> protocol.DataNopRequest
	7,  // 6: protocol.DataResponse.retrieve_request:type_name -> protocol.DataRetrieveRequest
	8,  // 7: protocol.DataResponse.retrieve_response:type_name -> protocol.DataRetrieveResponse
	9,  // 8: protocol.DataResponse.supply_request:type_name -> protocol.DataSupplyRequest
	11, // 9: protocol.DataResponse.delete_request:type_name -> protocol.DataDeleteRequest
	0,  // 10: protocol.ProxyUIntegration.Correlation:input_type -> protocol.CorrelationRequest
	2,  // 11: protocol.ProxyUIntegration.SubmitDocument:input_type -> protocol.SubmitDocumentRequest
	4,  // 12: protocol.ProxyUIntegration.Permission:input_type -> protocol.PermissionRequest
	14, // 13: protocol.ProxyUIntegration.Data:input_type -> protocol.DataRequest
	1,  // 14: protocol.ProxyUIntegration.Correlation:output_type -> protocol.CorrelationResponse
	3,  // 15: protocol.ProxyUIntegration.SubmitDocument:output_type -> protocol.SubmitDocumentResponse
	5,  // 16: protocol.ProxyUIntegration.Permission:output_type -> protocol.PermissionResponse
	15, // 17: protocol.ProxyUIntegration.Data:output_type -> protocol.DataResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_protocol_proxyu_proto_init() }
func file_protocol_proxyu_proto_init() {
	if File_protocol_proxyu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_proxyu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CorrelationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proxyu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CorrelationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proxyu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitDocumentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proxyu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitDocumentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proxyu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proxyu_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PermissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proxyu_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataField); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proxyu_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRetrieveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proxyu_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRetrieveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proxyu_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataSupplyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proxyu_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataSupplyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proxyu_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proxyu_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proxyu_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataNopRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proxyu_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_proxyu_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protocol_proxyu_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*CorrelationResponse_CorrelationMessage)(nil),
		(*CorrelationResponse_PublicKey)(nil),
	}
	file_protocol_proxyu_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*PermissionResponse_PermissionMessage)(nil),
		(*PermissionResponse_Granted)(nil),
	}
	file_protocol_proxyu_proto_msgTypes[14].OneofWrappers = []interface{}{
		(*DataRequest_RetrieveRequest)(nil),
		(*DataRequest_RetrieveResponse)(nil),
		(*DataRequest_SupplyResponse)(nil),
		(*DataRequest_DeleteResponse)(nil),
		(*DataRequest_NopRequest)(nil),
	}
	file_protocol_proxyu_proto_msgTypes[15].OneofWrappers = []interface{}{
		(*DataResponse_RetrieveRequest)(nil),
		(*DataResponse_RetrieveResponse)(nil),
		(*DataResponse_SupplyRequest)(nil),
		(*DataResponse_DeleteRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_proxyu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocol_proxyu_proto_goTypes,
		DependencyIndexes: file_protocol_proxyu_proto_depIdxs,
		MessageInfos:      file_protocol_proxyu_proto_msgTypes,
	}.Build()
	File_protocol_proxyu_proto = out.File
	file_protocol_proxyu_proto_rawDesc = nil
	file_protocol_proxyu_proto_goTypes = nil
	file_protocol_proxyu_proto_depIdxs = nil
}
